In [25]:
import numpy as np
from scipy.special import expit as sigmoid

In [8]:
X = np.identity(8)
y = X

In [84]:
def init_network(input_size, hidden_size, output_size):
    input = np.zeros((input_size, 1))
    hidden = np.zeros((hidden_size, 1))
    output = np.zeros((output_size, 1))
    network = list((input, hidden, output))
    return network
network = init_network(8,3,8)

In [30]:
network

[array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])]

In [56]:
def activation(inputs, weights, bias=True):
    
    if bias == True:
        term = 1
    else: 
        term = 0
    for input, weight in zip(inputs, weights):
        term += (input * weight)
    return sigmoid(term)

print(activation([1,0,0,0,0,0,0,0], np.zeros((8,1)), False))


[0.5]


In [88]:
def forward(network, input):
    for i in range(len(network)):
        if i == 0:
            network[i] = input
        else:
            for node in network[i]:
                node = activation(network[i-1], np.zeros(network[i-1].shape))
            print(network[i])
    return network

In [89]:
forward(network, X[0])

[[0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


[array([1., 0., 0., 0., 0., 0., 0., 0.]),
 array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])]

In [74]:
len(network)

3

In [79]:
network[1].shape

(3, 1)