In [25]:
import numpy as np
from scipy.special import expit as sigmoid

In [8]:
X = np.identity(8)
y = X

In [124]:
def init_network(input_size, hidden_size, output_size):
    input = np.zeros((input_size, 2))
    hidden = np.zeros((hidden_size, 2))
    output = np.zeros((output_size, 2))
    network = list((input, hidden, output))
    return network
network = init_network(8,3,8)
network

[array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])]

In [204]:
class Layer:
    def __init__(self, size, size_n1):
        self.activation = np.zeros((size, 1))
        self.weights = np.zeros((size, size_n1))
    
    def print_weights(self):
        print(self.weights)

class Network:
    def __init__(self, nodes) -> None:
        nodes = [nodes[i]+1 if i < len(nodes) - 1 else nodes[i] for i in range(len(nodes))]
        nodes.append(0)
        self.layers = []
        for i in range(len(nodes)-1):
            self.layers.append(Layer(nodes[i], nodes[i+1]))
    
    def activation(self, layer_int):
        layer = self.layers[layer_int]
        prev_layer = self.layers[layer_int -1]
        print(prev_layer.activation[:-1].shape, prev_layer.weights[:-1, :-1].shape)
        layer.activation = np.dot(prev_layer.activation.T[:, :-1], prev_layer.weights[:-1, :-1]) + prev_layer.weights[-1, -1]
        print(layer.activation)


Network([8,3,8]).activation(1)

(8, 1) (8, 3)
[[0. 0. 0.]]


In [123]:
def activation(inputs, weights, bias=True):
    
    if bias == True:
        term = 1
    else: 
        term = 0
    for input, weight in zip(inputs, weights):
        term += (input * weight)
    return sigmoid(term)



# activation function for top node hidden layer.
print(activation([1,0,0,0,0,0,0,0], np.zeros((8,1)), False))


[0.5]


In [121]:
def forward(network, input):
    for i in range(len(network)):
        if i == 0:
            network[i] = input
        elif i == 1:
            for node_i in range(len(network[i])):
                network[i][node_i] = activation(network[i-1], np.zeros(network[i-1].shape), bias=False)
        else: 
            for node_i in range(len(network[i])):
                network[i][node_i] = activation(network[i-1], np.zeros(network[i-1].shape))
    return network

In [184]:
sigmoid([1,0.5,0])

array([0.73105858, 0.62245933, 0.5       ])

In [194]:
activation = np.ones((1,8))
weights = np.ones((8,2))
np.dot(activation, weights)

array([[8., 8.]])