In [25]:
import numpy as np
from scipy.special import expit as sigmoid

In [8]:
X = np.identity(8)
y = X

In [124]:
def init_network(input_size, hidden_size, output_size):
    input = np.zeros((input_size, 2))
    hidden = np.zeros((hidden_size, 2))
    output = np.zeros((output_size, 2))
    network = list((input, hidden, output))
    return network
network = init_network(8,3,8)
network

[array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])]

In [322]:
np.random.seed(42)
class Layer:
    def __init__(self, size, size_n1):
        self.activation = np.zeros((size, 1))
        self.weights = np.random.rand(size, size_n1)
           
    
    def print_weights(self):
        print(self.weights)



class Network:
    def __init__(self, nodes) -> None:
        # add bias nodes to network
        #FIXME: Right now we're calculating for 4 hidden nodes, because of this addition.
        nodes = [nodes[i]+1 if i < len(nodes) - 1 else nodes[i] for i in range(len(nodes))]
        nodes.append(0)
        print('nr nodes: ', nodes)
        self.layers = []
        for i in range(len(nodes)-1):
            self.layers.append(Layer(nodes[i], nodes[i+1]))
    


    def activation(self, layer_int):
        layer = self.layers[layer_int]
        prev_layer = self.layers[layer_int -1]

        print('weights: ', prev_layer.weights, '\nactivation: ', prev_layer.activation)
        act_vector = np.dot(prev_layer.activation.T, prev_layer.weights)

        print('act_vector: ', sigmoid(act_vector))
        
        layer.activation = sigmoid(act_vector)

    def forward(self, input):
        input = input.reshape((input.shape[0], 1))
        self.layers[0].activation[:-1] = input
        self.layers[0].activation[-1] = 1
        for i in range(1, len(self.layers)):
            self.layers[i].activation = self.activation(i)



a = Network([8,3,8])
a.forward(np.array([1,0,0,0,0,0,0,0]))
# a.layers[2]

nr nodes:  [9, 4, 8, 0]
weights:  [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]] 
activation:  [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
act_vector:  [[0.60816174 0.86984623 0.84522442 0.80330116]]
weights:  [[0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691
  0.03438852 0.9093204 ]
 [0.25877998 0.66252228 0.31171108 0.52006802 0.54671028 0.18485446
  0.96958463 0.77513282]
 [0.93949894 0.89482735 0.59789998 0.92187424 0.0884925  0.19598286
  0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698]] 
activation:  None


AttributeError: 'NoneType' object has no attribute 'T'

In [123]:
def activation(inputs, weights, bias=True):
    
    if bias == True:
        term = 1
    else: 
        term = 0
    for input, weight in zip(inputs, weights):
        term += (input * weight)
    return sigmoid(term)



# activation function for top node hidden layer.
print(activation([1,0,0,0,0,0,0,0], np.zeros((8,1)), False))


[0.5]


In [121]:
def forward(network, input):
    for i in range(len(network)):
        if i == 0:
            network[i] = input
        elif i == 1:
            for node_i in range(len(network[i])):
                network[i][node_i] = activation(network[i-1], np.zeros(network[i-1].shape), bias=False)
        else: 
            for node_i in range(len(network[i])):
                network[i][node_i] = activation(network[i-1], np.zeros(network[i-1].shape))
    return network

In [314]:
np.ndarray((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [194]:
activation = np.ones((1,8))
weights = np.ones((8,2))
np.dot(activation, weights)

array([[8., 8.]])

In [259]:
np.random.rand(3,3)

array([[0.56735159, 0.49764832, 0.19076445],
       [0.50458865, 0.99448377, 0.73499222],
       [0.08844741, 0.33895126, 0.75708864]])